### ISSUE TITLE
How to build and test

### ISSUE THREAD

**Issue by flatiron32** [DRuggeri/netgear_client#1]
I am quite new to golang but I would like to contribute logout functionality to this module. I think the change is straightforward, but I cannot figure out how to build and test this module. Is there s specific version of go required? The latest version (1.17.6) ask me to initialize a module when I try to build or test.
I am happy to RTFM if you can point me in the right direction.
Thanks for all your hard work on this and the exporter.

**Comment by DRuggeri** [comment]
Hey there, @flatiron32. Thanks for checking in - and glad to see you're interested in contributing! I've gone ahead and initialed this as a new go module (for whatever reason, I'm still working locally on 1.14.x go environment). I have also added a quick word in the README about testing. When you give it a whirl, be sure to copy one of the other test cases to vet your new functionality as part of the PR.

Feel free to reopen if I can elaborate a bit more!
