### ISSUE TITLE
Trouble getting it to run

### ISSUE THREAD

**Issue by Crash1869** [DRuggeri/netgear_client#4]
Hello,

I am very new to golang and am trying to get the client to run so that I can connect it to the exporter and get that data flowing into grafana. Running a test works without any issues but when I attempt to run it I hit walls due to there being no main existing in the files that myself nor the command can see. Am I missing where it is located? I was trying to add func main() but because of how green I am in regards to this wasn't sure what needed to be there. Thanks for any insight.

**Comment by DRuggeri** [comment]
Hey there, @Crash1869  - so sorry for the slow reply. Because this is just a library, there is no main function by itself. It's a little complex, but if you'd like to see an example of the library in action, here is a Prometheus exporter that uses it: https://github.com/DRuggeri/netgear_exporter
